name: Atualizar Painel PH

on:
  workflow_dispatch:

  schedule:
    - cron: "0 */6 * * *"

permissions:
  contents: write

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Instalar Dependências
        run: |
          pip install -r requirements.txt

      - name: Rodar Buscador
        run: |
          python buscador.py

      - name: Commitar Atualizações
        run: |

          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

          git add .

          git commit -m "Atualização automática IPTV" || echo "Sem alterações"

          git push
